language: java
sudo: required
services:
- docker
- postgresql
before_install:
- openssl aes-256-cbc -K $encrypted_e3e46bd44864_key -iv $encrypted_e3e46bd44864_iv
  -in .build/test-settings.xml.enc -out ~/settings.xml -d
- docker pull sath89/oracle-xe-11g
- docker build -t sql2o-oracle ./extensions/oracle
- docker run -d --rm -p 1521:1521 --name=sql2o-oracle-xe-11g sql2o-oracle
before_script:
- psql -c "CREATE USER test WITH PASSWORD 'testtest';" -U postgres
- psql -c "CREATE DATABASE testdb WITH OWNER test;" -U postgres
install:
- mvn compile -B -V --settings ~/settings.xml
script:
- mvn test -B -V --settings ~/settings.xml
after_script:
- docker kill sql2o-oracle-xe-11g
env:
  global:
  - secure: FzC7HsjGh4ChsG/z+kzOfHY7R7x5+yULZAoCP58VNH2luvZkvypPia2XnLkrCe8WhqXq0BS5XOVnv/8xHOgdXhmk1RlhUKsz8i9CZ9pV8FQiShCdtbwRKPpizYR4mo5XXIBg/58UrAWcZPOQqR/Xf6cb4X18uAlVK1s4DCd18cw=
  - secure: d5JFReXqMkLcx3T65nJfcY9GbsqC+O1628CgOFNdG0tL9+FUnS0tAaddXck4LxrsMuySRsR654bW8edM2RxMym0smZ2meZMa2jTq9M6KOq0E4BOgwowndkJniZ8ROBJQKoSGAbGvYjJSmYmWOdPBYSOR3Xr1UsD6plDOaXMSXrg=
